

def Init():
    import Bladex
    import Reference
    print "Initialising scorer data"
    Bladex.ReadBitMap("../../Data/Icons/Bug.bmp","BugIcon")
    Bladex.ReadBitMap("../../Data/Icons/Chaos.bmp","ChaosIcon")
    Bladex.ReadBitMap("../../Data/Icons/Cosita.bmp","CosIcon")
    Bladex.ReadBitMap("../../Data/Icons/dalgurak.bmp","DalGurakIcon")
    Bladex.ReadBitMap("../../Data/Icons/enano1.bmp","DwarfIcon1")
    Bladex.ReadBitMap("../../Data/Icons/enano2.bmp","DwarfIcon2")
    Bladex.ReadBitMap("../../Data/Icons/enano3.bmp","DwarfIcon3")
    Bladex.ReadBitMap("../../Data/Icons/enano4.bmp","DwarfIcon4")
    Bladex.ReadBitMap("../../Data/Icons/Gdemon.bmp","GDemonIcon")
    Bladex.ReadBitMap("../../Data/Icons/Glm_cl.bmp","ClayGolemIcon")
    Bladex.ReadBitMap("../../Data/Icons/Glm_lv.bmp","LavaGolemIcon")
    Bladex.ReadBitMap("../../Data/Icons/Glm_mt.bmp","MetalGolemIcon")
    Bladex.ReadBitMap("../../Data/Icons/Glm_st.bmp","StoneGolemIcon")
    Bladex.ReadBitMap("../../Data/Icons/Glm_ic.bmp","IceGolemIcon")
    Bladex.ReadBitMap("../../Data/Icons/Gork.bmp","GorkIcon")
    Bladex.ReadBitMap("../../Data/Icons/icono caballero.bmp","KnightIcon")
    Bladex.ReadBitMap("../../Data/Icons/Icono Darklord.bmp","DarkLordIcon")
    Bladex.ReadBitMap("../../Data/Icons/icono prisionero.bmp","PrisonerIcon")
    Bladex.ReadBitMap("../../Data/Icons/Knight Dark.bmp","KnightDarkIcon")
    Bladex.ReadBitMap("../../Data/Icons/Knight zombie.bmp","KnightzombieIcon")
    Bladex.ReadBitMap("../../Data/Icons/Ldemon.bmp","LDemonIcon")
    Bladex.ReadBitMap("../../Data/Icons/lich.bmp","LichIcon")
    Bladex.ReadBitMap("../../Data/Icons/minotaur.bmp","MinotaurIcon")
    Bladex.ReadBitMap("../../Data/Icons/Orco.bmp","OrcIcon")
    Bladex.ReadBitMap("../../Data/Icons/Ork Dark.bmp","OrkDarkIcon")
    Bladex.ReadBitMap("../../Data/Icons/ragnar.bmp","RagnarIcon")
    Bladex.ReadBitMap("../../Data/Icons/salamander.bmp","SalamanderIcon")
    Bladex.ReadBitMap("../../Data/Icons/Skull.bmp","SkeletonIcon")
    Bladex.ReadBitMap("../../Data/Icons/Spider.bmp","SpiderIcon")
    Bladex.ReadBitMap("../../Data/Icons/Traidor.bmp","TraitorIcon")
    Bladex.ReadBitMap("../../Data/Icons/Troll.bmp","TrollIcon")
    Bladex.ReadBitMap("../../Data/Icons/Vamp.bmp","VampireIcon")
    Bladex.ReadBitMap("../../Data/Icons/Mortimer.bmp","MortimerIcon")
    Bladex.ReadBitMap("../../Data/Icons/NPKnight.bmp","NPKnightIcon")

    Reference.EnemiesDefaultScorerData['ChaosKnight']=("ChaosIcon","Chaos Knight")
    Reference.EnemiesDefaultScorerData['Cos']=("CosIcon","Boogie")
    Reference.EnemiesDefaultScorerData['DalGurak']=("DalGurakIcon","Dal Gurak")
    Reference.EnemiesDefaultScorerData['DarkLord']=("DarkLordIcon","AnAhkard")
    Reference.EnemiesDefaultScorerData['Dark_Knight']=("KnightDarkIcon","Dark Knight")
    Reference.EnemiesDefaultScorerData['Dark_Ork']=("OrkDarkIcon","Dark Orc")
    Reference.EnemiesDefaultScorerData['Enano1']=("DwarfIcon1","Dwarf")
    Reference.EnemiesDefaultScorerData['Enano2']=("DwarfIcon2","Dwarf")
    Reference.EnemiesDefaultScorerData['Enano3']=("DwarfIcon3","Dwarf")
    Reference.EnemiesDefaultScorerData['Enano4']=("DwarfIcon4","Dwarf")
    Reference.EnemiesDefaultScorerData['Golem_clay']=("ClayGolemIcon","Clay Golem")
    Reference.EnemiesDefaultScorerData['Golem_lava']=("LavaGolemIcon","Lava Golem")
    Reference.EnemiesDefaultScorerData['Golem_metal']=("MetalGolemIcon","Metal Golem")
    Reference.EnemiesDefaultScorerData['Golem_stone']=("StoneGolemIcon","Stone Golem")
    Reference.EnemiesDefaultScorerData['Golem_ice']=("IceGolemIcon","Ice Golem")
    Reference.EnemiesDefaultScorerData['Great_Demon']=("GDemonIcon","Great Demon")
    Reference.EnemiesDefaultScorerData['Great_Ork']=("GorkIcon","Great Orc")
    Reference.EnemiesDefaultScorerData['Knight']=("TraitorIcon","Knight")
    Reference.EnemiesDefaultScorerData['Knight_N']=("KnightIcon","Knight")
    Reference.EnemiesDefaultScorerData['Knight_Traitor']=("TraitorIcon","Traitor")
    Reference.EnemiesDefaultScorerData['Knight_Zombie']=("KnightzombieIcon","Knight living death ")
    Reference.EnemiesDefaultScorerData['Lich']=("LichIcon","Lich")
    Reference.EnemiesDefaultScorerData['Little_Demon']=("LDemonIcon","Spawn")
    Reference.EnemiesDefaultScorerData['Minotaur']=("MinotaurIcon","Minotaur")
    Reference.EnemiesDefaultScorerData['Ork']=("OrcIcon","Orc")
    Reference.EnemiesDefaultScorerData['Prisoner_1']=("PrisonerIcon","Prisoner")
    Reference.EnemiesDefaultScorerData['Prisoner_2']=("PrisonerIcon","Prisoner")
    Reference.EnemiesDefaultScorerData['Prisoner_3']=("PrisonerIcon","Prisoner")
    Reference.EnemiesDefaultScorerData['Prisoner_4']=("PrisonerIcon","Prisoner")
    Reference.EnemiesDefaultScorerData['Prisoner_5']=("PrisonerIcon","Prisoner")
    Reference.EnemiesDefaultScorerData['Prisoner_6']=("PrisonerIcon","Prisoner")
    Reference.EnemiesDefaultScorerData['Ragnar']=("RagnarIcon","Ragnar")
    Reference.EnemiesDefaultScorerData['Salamander']=("SalamanderIcon","Salamander")
    Reference.EnemiesDefaultScorerData['Skeleton']=("SkeletonIcon","Skeleton")
    Reference.EnemiesDefaultScorerData['Spidersmall']=("SpiderIcon","Spider")
    Reference.EnemiesDefaultScorerData['Troll_Dark']=("TrollIcon","Dark Troll")
    Reference.EnemiesDefaultScorerData['Troll_snow']=("TrollIcon","Snow Troll")
    Reference.EnemiesDefaultScorerData['Vamp']=("VampireIcon","Vampire")
    Reference.EnemiesDefaultScorerData['Mortimer']=("MortimerIcon","Sir Mortimer")
    Reference.EnemiesDefaultScorerData['NP_Knight']=("NPKnightIcon","Knight")
